### ISSUE TITLE
Deploy after error

### ISSUE THREAD

**Issue by igidas** [unadlib/ssh-webpack-plugin#1]
Hey, thanks for a plugin.

But there is a issue - plugin makes deploy even there is error in Webpack compilation.

**Comment by unadlib** [comment]
Can you tell me the details of the error?

**Comment by igidas** [comment]
It's not error of this plugin.
You should add a check to see if Webpack had errors in building the assets, if not - only then make a deploy.

**Comment by unadlib** [comment]
OK, thank you for your suggestion.
